language: node_js
node_js:
- lts/*
addons:
  ssh_known_hosts: schedar.uberspace.de
before_deploy:
- openssl aes-256-cbc -K $encrypted_63b3aa651d67_key -iv $encrypted_63b3aa651d67_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master
